import '@/assets/scss/style.scss';
import AppProvidersWrapper from '@/components/wrapper/AppProvidersWrapper';
import { DEFAULT_PAGE_TITLE } from '@/context/constants';
import { Roboto } from 'next/font/google';


const roboto = Roboto({
  display: 'swap',
  style: ['normal', 'italic'],
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900']
});
export const metadata = {
  title: {
    template: '%s | Foreshore - Admin Dashboard',
    default: DEFAULT_PAGE_TITLE
  },
  description: 'Generated by create next app'
};
export default function RootLayout({
  children
}) {

  return <html lang="en">
      <head>
       {/* <link rel="icon" href={logo}/>
       <link rel="apple-touch-icon" href={logo}/> */}
      </head>
      <body className={roboto.className}>
        <div id="__next_splash">
          <AppProvidersWrapper>{children}</AppProvidersWrapper>
        </div>
      </body>
    </html>;
}